server:
  port: '8080'

spring:
  application.name: ems-post-service
  datasource:
    username: sa
    url: jdbc:h2:file:~/post-service-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    password: '123'
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq